### ISSUE TITLE
Update the dependencies

### ISSUE THREAD

**Issue by PatheticMustan** [PatheticMustan/ScoutingApp2019#37]
Dependabot keeps bugging me, so somebody needs to update the dependencies manually. This should be easy peasy lemon squeasy, hopefully.

**Comment by 00100000spacebar** [comment]
WOWWWWWW. Thanks so much for the "ezpz" task, sorry I'm too dumb to handle REAL code work!

**Comment by PatheticMustan** [comment]
did you even finish it
